### ISSUE TITLE
Use volume keys for forward/back in presentations

### ISSUE THREAD

**Issue by jancborchardt** [justin-taylor/Android-remote-client#4]
The reason why I found this app is because I am looking for a means to use my Android phone as a simple presentation clicker. Basically it should just be a background app which, for the time it’s running, hijacks the volume keys.

Pressing volume-up should advance the presentation on the host computer one slide (send a cursor-right or space) and volume-down should go to the previous slide (cursor-left).

That would also be very helpful for photo slideshows for example. @justin-taylor do you plan to include anything like that?

**Comment by justin-taylor** [comment]
That feature doesn't really coincide with the goal of this project. This project is intended to allow a user to control the mouse and keyboard of a computer. What you are asking for is very specific to one particular use case.

I would consider adding the ability to change the volume of the remote computer using a device's volume rocker.
